# Generated by Django 5.0.6 on 2024-09-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('1', 'Others'), ('2', 'Java'), ('3', 'C++'), ('4', 'Javascripts'), ('5', 'MySQL'), ('6', 'Python')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
